name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy the app
        uses: actions/deploy-to-vercel@v1
        with:
          project_id: your_project_id
          token: your_access_token
